
name: backend_test
on:
  push:



jobs:
  version:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: 'sqlite'
      DB_DATABASE: '/tmp/backend_database.sqlite'
      DB_FOREIGN_KEYS: true
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ricom/toolbox-backend'
          path: 'backend'
      - uses: actions/checkout@v3
        with:
          repository: 'ricom/toolbox-frontend'
          path: 'frontend'
      - run: cd backend
      - name: Composer (php-actions)
        uses: php-actions/composer@v6
        with: 
          dev: 'no'
          php_version: "8.0"
          version: 2
          args: '--optimize-autoloader'
          working_dir: 'backend'
      - run: cp .env.example .env
      - run: 'php artisan key:generate'
      - run: 'php artisan migrate --seed'
      



