
name: backend_test
on:
  push:



jobs:
  test:
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: toolbox
        ports:
          - 3306:3306
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: 'root'
      DB_USERNAME: 'root'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ricom/toolbox-backend'
          path: 'backend'
      - uses: actions/checkout@v3
        with:
          repository: 'ricom/toolbox-frontend'
          path: 'frontend'
      - name: Composer (php-actions)
        uses: php-actions/composer@v6
        with: 
          dev: 'no'
          php_version: "8.0"
          version: 2
          args: '--optimize-autoloader'
          working_dir: 'backend'
      - name: setup backend
        working-directory: backend
        run: | 
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --seed
        
      



