name: bump version
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: "Welcher version"
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major



jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          bump-policy: 'ignore'
          default: ${{github.events.inputs.bumpType}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



